# Generated by Django 5.1.7 on 2025-03-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='liked',
            new_name='likes',
        ),
    ]
